[package]
name = "rustiq"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
eframe = "0.33"
flume = "0.11"
rustradio = "0.15"
num-complex = "0.4"

[dev-dependencies]
tempfile = "3.15"
